### PR TITLE
Configure Heroku ☁️ 

### PR DESCRIPTION
**Pull request by brittanylau**
Heroku configuration! When this PR goes in I'll enable automatic deploys in the Heroku UI, so that future PRs will go straight into the world ☁️ 

SQLite is still used for local development, but the deployed app will use Heroku Postgres. Mostly followed [this handy-dandy tutorial](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment)!

### CODE REVIEW

**Review by danielchen115 — APPROVED** [review]
_nice_

**Review by Tayef-Shah — APPROVED** [review]
LGTM!

**Review by annoyingpr — APPROVED** [review]
:shipit:

**Comment by brittanylau** [comment]
thanks for the support y'all 💛

**Pull request merged**
