### PR TITLE
Safe delete fields

### PR DESCRIPTION
**Pull request by Tayef-Shah**
### Notion ticket link

[Soft delete fields](https://www.notion.so/uwblueprintexecs/Soft-delete-fields-6f59dd0337fe480ab609b6e6be65a2f9)

### Implementation description

- Added [safe delete package ](https://github.com/makinacorpus/django-safedelete)
- By default fields are now soft deleted. There is a date time field called `deleted` on the field model which indicates when a field was marked as deleted. They are not actually deleted from the db.
- we can undelete fields via the Django admin or we could add an endpoint to undelete them

### Steps to test

1. Build and run the container `docker-compose up -d --build`
2. Login to the admin
3. Go to `localhost:8000/fields/{id}` and pick whatever id you like (as long as it exists)
4. Delete the field
5. Go back to the admin and check that the field you deleted was highlighted as deleted
6. Try undeleting it from admin (select and undelete from admin actions)
image

### What should reviewers focus on?

- testing

### Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] I have run the linter
- [x] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by jolenezheng — COMMENTED** [review]
After I delete it, if I open it again in django admin and click "save" (with or without making changes) it automatically undeletes this. Is this expected :0

**Comment by Tayef-Shah** [comment]
> After I delete it, if I open it again in django admin and click "save" (with or without making changes) it automatically undeletes this. Is this expected :0

Yeah this is expected behaviour... not 100% sure if it's desired though

**Comment by brittanylau** [comment]
> Yeah this is expected behaviour... not 100% sure if it's desired though

I think this is ok, we'll make sure to document this so users are aware what's happening :)

**Review by brittanylau — APPROVED** [review]

**Comment by Tayef-Shah** [comment]
> > Yeah this is expected behaviour... not 100% sure if it's desired though
> 
> I think this is ok, we'll make sure to document this so users are aware what's happening :)

ok cool. If we ever want to change this behaviour you just need to set `SAFE_DELETE_INTERPRET_UNDELETED_OBJECTS_AS_CREATED = False` in the base settings file

**Pull request merged**
