### PR TITLE
Family details sidebar notes section

### PR DESCRIPTION
**Pull request by hyunzeekim**
### Notion ticket link

[Notes Section](https://www.notion.so/uwblueprintexecs/Notes-section-694b94f92367427fb0852ebf5fe0c095)

### Implementation description

- Added notes section to family details

### Steps to test

1. Verify text in notes field for families

### What should reviewers focus on?

- Clean & robust code, correctness, test coverage

### Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] I have run the linter
- [x] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by Tayef-Shah** [comment]
@hyunzeekim remember to commit the migration file

**Comment by hyunzeekim** [comment]
> @hyunzeekim remember to commit the migration file

whoops sorry I missed that! will commit those

**Comment by Tayef-Shah** [comment]
I suppose we need to try to rollback again and try a different strategy to remigrate

**Comment by Tayef-Shah** [comment]
Hi y'all, I moved this PR to #78

**Pull request closed without merging**
